# Generated by Django 5.0.6 on 2024-06-25 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarrierData',
            fields=[
                ('carrier_id', models.IntegerField(primary_key=True, serialize=False)),
                ('carrier_name', models.CharField(max_length=100)),
                ('country_name', models.CharField(max_length=100)),
                ('ecpc_recent', models.FloatField()),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('on_record', models.BigIntegerField(default=0)),
            ],
        ),
    ]
